name: Build-Apk
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
