name: Build-Apk
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  build:
    runs-on: macos-11
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            distribution: 'adopt'
            java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the app
        run: ./gradlew assembleDebug

      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-


      - name: Upload debug apk
        uses: actions/upload-artifact@v2
        if: ${{ !github.head_ref }}
        with:
          name: apk-debug
          path: app/build/outputs/apk/debug
