name: Android CI

on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run git
      run: git add --all
    - name: commit
      run: git commit -m "ok"
    - name: push
      run: git push
